apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
data:
  ARTEMIS_USER: {{ .Values.config.ARTEMIS_USER | quote}}