apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "artemis.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}