apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis.fullname" . }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
type: Opaque
data:
  ARTEMIS_PASSWORD: {{ .Values.config.ARTEMIS_PASSWORD | quote}}