apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "artemis.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
