apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}-messaging
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.messaging.type }}
  ports:
    - port: {{ .Values.service.messaging.port }}
      targetPort: artemis
      protocol: TCP
      name: artemis
  selector:
    {{- include "artemis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}-console
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.console.type }}
  ports:
    - port: {{ .Values.service.console.port }}
      targetPort: console
      nodePort: {{ .Values.service.console.nodePort }}
      protocol: TCP
      name: console
  selector:
    {{- include "artemis.selectorLabels" . | nindent 4 }}