apiVersion: v1
kind: ConfigMap
metadata:
  name: infra
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fib.labels" . | nindent 4 }}
data:
  BROKER_URL: "tcp://{{ .Values.global.infra.namespace}}-artemis-messaging.{{ .Values.global.infra.namespace}}:61616"
  BROKER_USER: {{ .Values.global.infra.broker.user  | quote }}
  REDIS_HOST: "{{ .Values.global.infra.namespace}}-redis.{{ .Values.global.infra.namespace}}"
  REDIS_PORT: "6379"
  POSTGRES_USER: {{ .Values.global.infra.postgres.user | quote }}