apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fib.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
      {{- include "fib.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.global.namespace }}-front
              port:
                number: 8080
        - path: /api/?(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.global.namespace }}-manager
              port:
                number: 8080