apiVersion: v1
kind: Secret
metadata:
  name: infra
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fib.labels" . | nindent 4 }}
type: Opaque
data:
  BROKER_PASSWORD: {{ .Values.global.infra.broker.password | quote}}
  POSTGRES_PASSWORD: {{ .Values.global.infra.postgres.password | quote}}