apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote}}