image:
  repository: golenski/fibonacci-msg-relay
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 500Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 5
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}

config:
  JOB_QUEUE_NAME: "job"
  LOGGING_LEVEL: "info"
