apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.config.PGADMIN_DEFAULT_EMAIL | quote}}