apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.config.PGADMIN_DEFAULT_PASSWORD | quote}}