apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "msg-relay.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "msg-relay.labels" . | nindent 4 }}
data:
  JOB_QUEUE_NAME: {{ .Values.config.JOB_QUEUE_NAME | quote }}
  POSTGRES_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.global.infra.namespace }}-postgres.{{ .Values.global.infra.namespace }}:5432/task_manager"
  LOGGING_LEVEL: {{ .Values.config.LOGGING_LEVEL | quote }}
  JVM_OPTS: "-XX:MaxRAMPercentage=75"