# Default values for worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3

image:
  repository: golenski/fibonacci-worker
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 500Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 5
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}

infra:


config:
  JOB_QUEUE_NAME: "job"
  JOB_RESULT_QUEUE_NAME: "job-result"
  WORKER_CONCURRENCY: "1-2"
  LOGGING_LEVEL: "info"