apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  JOB_QUEUE_NAME: {{ .Values.config.JOB_QUEUE_NAME | quote}}
  JOB_RESULT_QUEUE_NAME: {{ .Values.config.JOB_RESULT_QUEUE_NAME | quote}}
  WORKER_CONCURRENCY: {{ .Values.config.WORKER_CONCURRENCY | quote}}
  LOGGING_LEVEL: {{ .Values.config.LOGGING_LEVEL | quote}}
  JVM_OPTS: "-XX:MaxRAMPercentage=75"